# Generated by Django 4.2.1 on 2023-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "year_in_school",
                    models.CharField(
                        choices=[
                            ("p", "Poor"),
                            ("vp", "Very Poor"),
                            ("m", "Mid"),
                            ("R", " Rich"),
                            ("vr", "Very Rich"),
                        ],
                        default="mid",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
