# Generated by Django 4.2.1 on 2023-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_student"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student", old_name="year_in_school", new_name="Finances",
        ),
    ]
