# Generated by Django 4.2.1 on 2023-05-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_year_in_school_student_finances"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Finances",
            field=models.CharField(
                choices=[
                    ("Poor", "Poor"),
                    ("Very Poor", "Very Poor"),
                    ("Normal", "Mid"),
                    ("Rich", " Rich"),
                    ("Very Rich", "Very Rich"),
                ],
                default="mid",
                max_length=9,
            ),
        ),
    ]
