# Generated by Django 4.2.1 on 2023-06-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_article_thumb"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drivers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                (
                    "team",
                    models.CharField(
                        choices=[
                            ("RedBull", "Redbull"),
                            ("Mercedes", "Mercedes"),
                            ("Aston Martin", "Aston Martin"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
