# Generated by Django 4.2.1 on 2023-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_drivers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivers",
            name="team",
            field=models.CharField(
                choices=[
                    ("RedBull", "Redbull"),
                    ("Mercedes", "Mercedes"),
                    ("AstonMartin", "Aston Martin"),
                    ("Ferrari", "Ferrari"),
                    ("AlphaTauri", "Alpha Tauri"),
                    ("AlphaRomeo", "Alpha Romeo"),
                    ("Williams", "Williams"),
                    ("Hass", "Hass"),
                    ("McLaren", "McLaren"),
                    ("Alpine", "Alpine"),
                ],
                max_length=20,
            ),
        ),
    ]
