# Generated by Django 4.2.1 on 2023-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_drivers_thumb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivers",
            name="thumb",
            field=models.ImageField(
                blank=True, default="default_f1.jpeg", upload_to=""
            ),
        ),
    ]
